### ISSUE TITLE
Capture Card Parsed as Video Controller

### ISSUE THREAD

**Issue by RPDak** [RPDak/PictoBox-OoT-Item-Viewer#6]
It seems capture cards (and some external cameras for  that matter) are counted as video controllers rather than genuine imaging devices. We'll need to get around this somehow as cv2.VideoCapture only picks up imaging devices. Looking into the use of FFMPEG-python or something similar as it seems to be able to look at usb devices indescriminantly.

**Comment by ColinT** [comment]
Resolved via #7
